-- Cost Seg Trust: initial schema
-- Works on any Postgres 14+ (Supabase, Neon, RDS). The app connects with a
-- server-side connection string only; nothing here is exposed to browsers.

create extension if not exists pgcrypto;
create extension if not exists citext;

-- Deal stages mirror the HubSpot pipeline one-to-one.
do $$ begin
  create type deal_stage as enum (
    'new_request', 'waiting_on_quotes', 'quotes_received', 'comparison_ready',
    'awaiting_approval', 'sent_to_client', 'closed'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type closed_outcome as enum ('won', 'lost');
exception when duplicate_object then null; end $$;

-- One row per person who requests quotes. Email is the dedupe key, matching
-- how HubSpot dedupes contacts.
create table if not exists clients (
  id                 uuid primary key default gen_random_uuid(),
  email              citext not null unique,
  first_name         text not null,
  last_name          text not null default '',
  phone              text,
  hubspot_contact_id text unique,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create sequence if not exists deal_number_seq start 1001;

create table if not exists deals (
  id                    uuid primary key default gen_random_uuid(),
  number                integer not null unique default nextval('deal_number_seq'),
  -- Generated by the browser for each form load; a double-click or retry
  -- with the same key never creates a second deal.
  request_key           uuid not null unique,
  client_id             uuid not null references clients(id),
  stage                 deal_stage not null default 'new_request',
  closed_outcome        closed_outcome,
  property_address      text not null,
  property_city_state   text,
  property_type         text not null,
  purchase_price        numeric(14,2) not null check (purchase_price > 0),
  placed_in_service     date not null,
  land_value            text,
  renovation_spend      numeric(14,2),
  has_cpa               boolean,
  client_notes          text,
  consent_contact       boolean not null,
  consent_at            timestamptz not null,
  utm_source            text,
  utm_medium            text,
  utm_campaign          text,
  admin_notes           text,
  hubspot_deal_id       text unique,
  hubspot_sync_status   text not null default 'pending' check (hubspot_sync_status in ('pending','synced','failed','skipped')),
  hubspot_synced_at     timestamptz,
  hubspot_error         text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
create index if not exists deals_stage_idx on deals(stage);
create index if not exists deals_created_idx on deals(created_at desc);

-- Audit trail shown on the deal page.
create table if not exists deal_events (
  id          bigserial primary key,
  deal_id     uuid not null references deals(id) on delete cascade,
  kind        text not null,
  detail      jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);
create index if not exists deal_events_deal_idx on deal_events(deal_id, created_at);

-- Every email/SMS the system tries to send, with its result.
create table if not exists notifications (
  id           bigserial primary key,
  deal_id      uuid references deals(id) on delete cascade,
  channel      text not null check (channel in ('email','sms')),
  recipient    text not null,
  purpose      text not null,
  status       text not null check (status in ('sent','failed','skipped')),
  provider_id  text,
  error        text,
  created_at   timestamptz not null default now()
);

create table if not exists suppliers (
  id            uuid primary key default gen_random_uuid(),
  company_name  text not null,
  contact_name  text,
  email         citext not null unique,
  phone         text,
  description   text,
  is_test       boolean not null default false,
  active        boolean not null default true,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Stage 2 (supplier quoting). Created now so the structure is complete.
-- Suppliers reach their invite through a personalized link; only a SHA-256
-- hash of the token is stored.
create table if not exists supplier_invites (
  id              uuid primary key default gen_random_uuid(),
  deal_id         uuid not null references deals(id) on delete cascade,
  supplier_id     uuid not null references suppliers(id),
  token_hash      text not null unique,
  status          text not null default 'invited' check (status in ('invited','viewed','submitted','declined','expired')),
  invited_at      timestamptz not null default now(),
  due_at          timestamptz not null default now() + interval '40 hours',
  reminder_sent_at timestamptz,
  viewed_at       timestamptz,
  responded_at    timestamptz,
  unique (deal_id, supplier_id)
);

create table if not exists supplier_quotes (
  id                         uuid primary key default gen_random_uuid(),
  invite_id                  uuid not null unique references supplier_invites(id) on delete cascade,
  fee                        numeric(12,2),
  study_type                 text,
  site_visit                 boolean,
  turnaround_days            integer,
  reclassified_pct           numeric(5,2),
  est_first_year_deduction   numeric(14,2),
  est_first_year_tax_savings numeric(14,2),
  assumed_tax_rate           numeric(5,2),
  audit_support              text,
  includes_lookback          boolean,
  payment_terms              text,
  valid_days                 integer,
  comments                   text,
  proposal_file_path         text,
  ai_extracted               jsonb,
  ai_filled_fields           text[] not null default '{}',
  submitted_at               timestamptz not null default now()
);

-- Stage 3 (AI comparison + approval).
create table if not exists comparisons (
  id             uuid primary key default gen_random_uuid(),
  deal_id        uuid not null unique references deals(id) on delete cascade,
  status         text not null default 'draft' check (status in ('draft','approved','sent')),
  summary        text,
  hidden_rows    text[] not null default '{}',
  hidden_invites uuid[] not null default '{}',
  overrides      jsonb not null default '{}'::jsonb,
  anonymize      boolean not null default false,
  approved_at    timestamptz,
  sent_at        timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- Small key/value store (e.g. cached HubSpot pipeline and stage ids).
create table if not exists app_settings (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz not null default now()
);

create or replace function touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

do $$
declare t text;
begin
  foreach t in array array['clients','deals','suppliers','comparisons'] loop
    execute format('drop trigger if exists %I_touch on %I', t, t);
    execute format('create trigger %I_touch before update on %I for each row execute function touch_updated_at()', t, t);
  end loop;
end $$;

-- Supabase exposes the public schema through its REST API to the "anon" and
-- "authenticated" roles. This app never uses that API, so lock every table
-- with row level security and no policies: only the server connection
-- (table owner) can read or write.
do $$
declare t text;
begin
  foreach t in array array['clients','deals','deal_events','notifications','suppliers','supplier_invites','supplier_quotes','comparisons','app_settings'] loop
    execute format('alter table %I enable row level security', t);
  end loop;
end $$;
